### ISSUE TITLE
I'm in trouble, please help me!

### ISSUE THREAD

**Issue by tohkahznu** [dysphie/nmrih-backpack2#1]
Thank you for repairing the backpack plug-in, but it seems that I can't compile successfully. Please see my error prompt log:

`//// backpack.sp
//

// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(724) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(737) : warning 229: index tag mismatch (symbol "tuple")
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(753) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(757) : warning 229: index tag mismatch (symbol "backpack_type")
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(758) : warning 229: index tag mismatch (symbol "backpack_type")
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(759) : warning 229: index tag mismatch (symbol "backpack_type")
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(760) : warning 229: index tag mismatch (symbol "backpack_type")
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(1012) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(1017) : warning 229: index tag mismatch (symbol "init")
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(1997) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(1998) : warning 229: index tag mismatch (symbol "tuple")
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(2000) : warning 229: index tag mismatch (symbol "tuple")
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(2001) : warning 229: index tag mismatch (symbol "tuple")
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(2002) : warning 229: index tag mismatch (symbol "tuple")
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(2003) : warning 229: index tag mismatch (symbol "tuple")
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(2628) : warning 209: function "IsEntityZombie" should return a value
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(2808) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(2812) : warning 229: index tag mismatch (symbol "tuple")
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(2945) : error 092: number of arguments does not match definition
// C:\Steam\nmrih\addons\sourcemod\scripting\backpack.sp(1070) : warning 204: symbol is assigned a value that is never used: "g_cvar_backpack_supply_drop_cooldown"
//
// 1 Error.
//
// Compilation Time: 0.44 sec
// ----------------------------------------`

How can I solve it? Please help me! thank you!

**Comment by dysphie** [comment]
Hi, the plugin compiles fine for me using SourcePawn Compiler 1.11.0.6655, try [upgrading](https://www.sourcemod.net/downloads.php?branch=dev) yours.
There are also compiled binaries in the [releases section](https://github.com/dysphie/nmrih-backpack-ex/releases).
