### ISSUE TITLE
[bug]Sometimes when I take ammunition out of my backpack, it disappears on me.

### ISSUE THREAD

**Issue by TsukasaSato1** [dysphie/nmrih-backpack2#13]
Sometimes when I take out the ammunition from my backpack and press the number 2 key to check it, the ammunition disappears and I can't see it anymore.

**Comment by dysphie** [comment]
Hi, is this no longer an issue?

**Comment by TsukasaSato1** [comment]
Yeah, that’s right. It wasn’t an issue. I later realized that it was actually caused by me using a different plugin that modified the weapon’s magazine attachment.
