### ISSUE TITLE
A new problem

### ISSUE THREAD

**Issue by tohkahznu** [dysphie/nmrih-backpack2#2]
The game has been updated and the plug-in doesn't work properly
Is your side working normally?

logs
`L 11/01/2021 - 10:38:08: SourceMod error session started
L 11/01/2021 - 10:38:08: Info (map "nmo_suzhou") (file "C:\steam\steamapps\common\No More Room in Hell Dedicated Server\nmrih\addons\sourcemod\logs\errors_20211101.log")
L 11/01/2021 - 10:38:08: [SM] Exception reported: Failed to create DHook for CItem_AmmoBox::FallInit
L 11/01/2021 - 10:38:08: [SM] Blaming: backpack.smx
L 11/01/2021 - 10:38:08: [SM] Call stack trace:
L 11/01/2021 - 10:38:08: [SM]   [0] SetFailState
L 11/01/2021 - 10:38:08: [SM]   [1] Line 3651, backpack.sp::DHookCreateFromConfOrFail
L 11/01/2021 - 10:38:08: [SM]   [2] Line 1129, backpack.sp::LoadPluginGamedata
L 11/01/2021 - 10:38:08: [SM]   [3] Line 982, backpack.sp::OnPluginStart
L 11/01/2021 - 10:38:08: [SM] Unable to load plugin "backpack.smx": Error detected in plugin startup (see error logs)
L 11/01/2021 - 10:38:32: SourceMod error session started
L 11/01/2021 - 10:38:32: Info (map "nmo_suzhou") (file "C:\steam\steamapps\common\No More Room in Hell Dedicated Server\nmrih\addons\sourcemod\logs\errors_20211101.log")
L 11/01/2021 - 10:38:32: [SM] Exception reported: Failed to create DHook for CItem_AmmoBox::FallInit
L 11/01/2021 - 10:38:32: [SM] Blaming: backpack.smx
L 11/01/2021 - 10:38:32: [SM] Call stack trace:
L 11/01/2021 - 10:38:32: [SM]   [0] SetFailState
L 11/01/2021 - 10:38:32: [SM]   [1] Line 3651, backpack.sp::DHookCreateFromConfOrFail
L 11/01/2021 - 10:38:32: [SM]   [2] Line 1129, backpack.sp::LoadPluginGamedata
L 11/01/2021 - 10:38:32: [SM]   [3] Line 982, backpack.sp::OnPluginStart
L 11/01/2021 - 10:38:32: [SM] Unable to load plugin "backpack.smx": Error detected in plugin startup (see error logs)
L 11/01/2021 - 10:38:33: SourceMod error session started
L 11/01/2021 - 10:38:33: Info (map "nmo_suzhou") (file "C:\steam\steamapps\common\No More Room in Hell Dedicated Server\nmrih\addons\sourcemod\logs\errors_20211101.log")
L 11/01/2021 - 10:38:33: [SM] Exception reported: Failed to create DHook for CItem_AmmoBox::FallInit
L 11/01/2021 - 10:38:33: [SM] Blaming: backpack.smx
L 11/01/2021 - 10:38:33: [SM] Call stack trace:
L 11/01/2021 - 10:38:33: [SM]   [0] SetFailState
L 11/01/2021 - 10:38:33: [SM]   [1] Line 3651, backpack.sp::DHookCreateFromConfOrFail
L 11/01/2021 - 10:38:33: [SM]   [2] Line 1129, backpack.sp::LoadPluginGamedata
L 11/01/2021 - 10:38:33: [SM]   [3] Line 982, backpack.sp::OnPluginStart
L 11/01/2021 - 10:38:33: [SM] Unable to load plugin "backpack.smx": Error detected in plugin startup (see error logs)
L 11/01/2021 - 11:18:04: Error log file session closed.`

**Comment by dysphie** [comment]
Fixed in [v2.0.0](https://github.com/dysphie/nmrih-backpack2/releases/tag/2.0.0)
