### ISSUE TITLE
packpacks dropped by zombies cannot be opened

### ISSUE THREAD

**Issue by zeThijs** [dysphie/nmrih-backpack2#8]
Pressing 'e' picks them up like a general prop_physics
Error code thrown:

L 01/25/2022 - 13:49:30: [SM] Exception reported: Client index 669 is invalid
L 01/25/2022 - 13:49:30: [SM] Blaming: nmrih-backpack2.smx
L 01/25/2022 - 13:49:30: [SM] Call stack trace:
L 01/25/2022 - 13:49:30: [SM]   [0] AreClientCookiesCached
L 01/25/2022 - 13:49:30: [SM]   [1] Line 1455, nmrih-backpack2.sp::ClientWantsHints
L 01/25/2022 - 13:49:30: [SM]   [2] Line 339, nmrih-backpack2.sp::Backpack::Drop
L 01/25/2022 - 13:49:30: [SM]   [3] Line 1527, nmrih-backpack2.sp::OnNPCKilled

**Comment by dysphie** [comment]
Hi, this issue has been resolved in 2.0.8, thanks for reporting!
